# Installing Pandas

using pip:

Pip install pandas
!pip install pandas

unising pip3 :
pip 3 install pandas

conda install pandas :
using Conda

# Series

In [6]:
import pandas as pd
Data_01 = (1,2,3,4,5)
Series  = pd.Series(Data_01)
Series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
import pandas as pd
Data_01 = {"KEY_1":1,"KEY_2":2,"KEY_3":3}
Data_01
pd.Series(Data_01)

KEY_1    1
KEY_2    2
KEY_3    3
dtype: int64

In [ ]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}
calSeries = pd.Series(calories,)
calories

{'day1': 420, 'day2': 380, 'day3': 390}

# Data Frame

In [5]:
import pandas as pd
data = {"calories" : [420, 380, 390],
        "duration" : [50,  40,   45]}
df = pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       390        45

In [6]:
new_Dict = {'Name':["Rajesh","Sunil","Prakash"],
            "Age":[20,30,40]}

df = pd.DataFrame(new_Dict)
df

      Name  Age
0   Rajesh   20
1    Sunil   30
2  Prakash   40

In [6]:
# Create Dataframe from Dictionary

Data = {"calories" : [420, 380, 390],
        "duration" : [30, 40, 45]}
df = pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       390        45

In [7]:
# Create Dataframe from List

listInsideLIST = [ ["Alice", 25],
                  ["Bob",30],
                  ["Charlie", 22],
                  ["David", 35]   ]
pd.DataFrame(listInsideLIST, columns=['Name', "Age"])

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   22
3    David   35

In [8]:
newDict = {'name': ['Alice', 'bob', 'Charlie', 'David'],
           'age': [25, 30, 22, 35]}
pd.DataFrame(newDict)

      name  age
0    Alice   25
1      bob   30
2  Charlie   22
3    David   35

# Reading And Saving DataFrame

In [8]:
File_path = "C:/Users/Niket/Downloads/Small Airline.csv"
df = pd.read_csv(File_path)
df

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
0,Ram,Kumar,42.0,BANGALURU,IndiGo,24-03-2019,22:20,01:10:00,22,20,1,10,Ram-Kumar
1,Mohan,Sharma,52.0,CHENNAI,Air India,01-05-2019,05:50,13:15,5,50,13,15,Mohan-Sharma
2,Tina,Ali,36.0,Pune,Jet Airways,09-06-2019,09:25,04:25:00,9,25,4,25,Tina-Ali
3,Jeetu,Gandhi,NaN,Delhi,IndiGo,12-05-2019,18:05,23:30,18,5,23,30,Jeetu-Gandhi
4,Meera,Kumari,NaN,LUCKNOW,IndiGo,01-03-2019,16:50,21:35,16,50,21,35,Meera-Kumari
5,Ram,Kumar,42.0,BANGALURU,NaN,24-03-2019,22:20,01:10:00,22,20,1,10,Ram-Kumar
6,Mohan,Sharma,52.0,CHENNAI,NaN,01-05-2019,05:50,13:15,5,50,13,15,Mohan-Sharma
7,Rajesh,Pawar,39.0,NaN,Jet Airways,01-03-2019,05:05,08:00,5,5,8,0,Rajesh-Pawar
8,Sanjay,Patil,43.0,NaN,Jet Airways,12-03-2019,08:55,10:25,8,55,10,25,Sanjay-Patil
9,Trishul,Shinde,45.0,Pune,Multiple carriers,27-05-2019,11:25,19:15,11,25,19,15,Trishul-Shinde
10,Sameer,Patil,39.0,Delhi,Jet Airways,12-03-2019,10:25,18:55,10,25,18,55,Sameer-Patil
11,Amol,Mahul,40.0,LUCKNOW,Jet Airways,01-03-2019,05:05,08:00,5,5,8,0,Amol-Mahul
12,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,12-03-2019,08:55,10:25,8,55,10,25,Praveen-Gurjar
13,Sunita,Patil,40.0,CHENNAI,Multiple carriers,27-05-2019,11:25,19:15,11,25,19,15,Sunita-Patil
14,Amol,Mahul,40.0,LUCKNOW,Jet Airways,01-03-2019,05:05,08:00,5,5,8,0,Amol-Mahul
15,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,12-03-2019,08:55,10:25,8,55,10,25,Praveen-Gurjar
16,Sunita,Patil,40.0,CHENNAI,Multiple carriers,27-05-2019,11:25,19:15,11,25,19,15,Sunita-Patil

In [5]:
file_path = "C:/Users/Niket/Downloads/Small Airline.xlsx"
df = pd.read_excel(file_path)

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Niket/Downloads/Small Airline.xlsx'

In [11]:
df
df.to_csv("C:/Users/Niket/Downloads/Small Airline.csv")

# Data Exproration

In [11]:
df.columns

Index(['First_name', 'Last_name', 'Age', 'City', 'Airline', 'Date_of_Journey',
       'Dep_Time', 'Arrival_Time', 'Dept_Hour', 'Dept_Minute', 'Arrival_Hour',
       'Arrival_Minute', 'Full Name'],
      dtype='str')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   First_name       17 non-null     str
 1   Last_name        17 non-null     str
 2   Age              15 non-null     float64
 3   City             15 non-null     str
 4   Airline          15 non-null     str
 5   Date_of_Journey  17 non-null     str
 6   Dep_Time         17 non-null     str
 7   Arrival_Time     17 non-null     str
 8   Dept_Hour        17 non-null     int64
 9   Dept_Minute      17 non-null     int64
 10  Arrival_Hour     17 non-null     int64
 11  Arrival_Minute   17 non-null     int64
 12  Full Name        17 non-null     str
dtypes: float64(1), int64(4), str(8)
memory usage: 1.9 KB

In [16]:
df.value_counts()

First_name  Last_name  Age   City       Airline            Date_of_Journey  Dep_Time  Arrival_Time  Dept_Hour  Dept_Minute  Arrival_Hour  Arrival_Minute  Full Name
Amol        Mahul      40.0  LUCKNOW    Jet Airways        01-03-2019       05:05     08:00         5          5            8             0               Amol-Mahul        2
Praveen     Gurjar     47.0  BANGALURU  Jet Airways        12-03-2019       08:55     10:25         8          55           10            25              Praveen-Gurjar    2
Sunita      Patil      40.0  CHENNAI    Multiple carriers  27-05-2019       11:25     19:15         11         25           19            15              Sunita-Patil      2
Ram         Kumar      42.0  BANGALURU  IndiGo             24-03-2019       22:20     01:10:00      22         20           1             10              Ram-Kumar         1
Mohan       Sharma     52.0  CHENNAI    Air India          01-05-2019       05:50     13:15         5          50           13            15              Mohan-Sharma      1
Tina        Ali        36.0  Pune       Jet Airways        09-06-2019       09:25     04:25:00      9          25           4             25              Tina-Ali          1
Trishul     Shinde     45.0  Pune       Multiple carriers  27-05-2019       11:25     19:15         11         25           19            15              Trishul-Shinde    1
Sameer      Patil      39.0  Delhi      Jet Airways        12-03-2019       10:25     18:55         10         25           18            55              Sameer-Patil      1
Name: count, dtype: int64

In [17]:
df.describe()

             Age  Dept_Hour  Dept_Minute  Arrival_Hour  Arrival_Minute
count  15.000000  17.000000    17.000000     17.000000       17.000000
mean   42.933333  10.529412    29.411765     12.058824       18.529412
std     4.757951   5.724046    19.193289      6.859943       14.004989
min    36.000000   5.000000     5.000000      1.000000        0.000000
25%    40.000000   5.000000    20.000000      8.000000       10.000000
50%    42.000000   9.000000    25.000000     10.000000       15.000000
75%    46.000000  11.000000    50.000000     19.000000       25.000000
max    52.000000  22.000000    55.000000     23.000000       55.000000

In [18]:
df['Dept_Hour'].unique

<bound method Series.unique of 0     22
1      5
2      9
3     18
4     16
5     22
6      5
7      5
8      8
9     11
10    10
11     5
12     8
13    11
14     5
15     8
16    11
Name: Dept_Hour, dtype: int64>

In [20]:
import sys
print(sys.executable)
%pip install --upgrade jinja2

c:\Program Files\Python314\python.exe
Defaulting to user installation because normal site-packages is not writeable
Collecting jinja2
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting MarkupSafe>=2.0 (from jinja2)
  Downloading markupsafe-3.0.4-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading markupsafe-3.0.4-cp314-cp314-win_amd64.whl (14 kB)
Installing collected packages: MarkupSafe, jinja2

   -------------------- ------------------- 1/2 [jinja2]
   -------------------- ------------------- 1/2 [jinja2]
   ---------------------------------------- 2/2 [jinja2]

Successfully installed MarkupSafe-3.0.4 jinja2-3.1.6
Note: you may need to restart the kernel to use updated packages.

In [22]:
list1 = [1,2,3,4,5] 
sereis = pd.Series(list1)
sereis.median()

np.float64(3.0)

In [23]:
list1 = [1,2,3,4,5]
sereis = pd.Series(list1)
sereis.mean()

np.float64(3.0)

In [24]:
df['Airline'].value_counts()
df['Airline'].mode()

0    Jet Airways
Name: Airline, dtype: str

In [25]:
df['Airline'].value_counts()

Airline
Jet Airways          8
IndiGo               3
Multiple carriers    3
Air India            1
Name: count, dtype: int64

In [26]:
df

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
0,Ram,Kumar,42.0,BANGALURU,IndiGo,24-03-2019,22:20,01:10:00,22,20,1,10,Ram-Kumar
1,Mohan,Sharma,52.0,CHENNAI,Air India,01-05-2019,05:50,13:15,5,50,13,15,Mohan-Sharma
2,Tina,Ali,36.0,Pune,Jet Airways,09-06-2019,09:25,04:25:00,9,25,4,25,Tina-Ali
3,Jeetu,Gandhi,NaN,Delhi,IndiGo,12-05-2019,18:05,23:30,18,5,23,30,Jeetu-Gandhi
4,Meera,Kumari,NaN,LUCKNOW,IndiGo,01-03-2019,16:50,21:35,16,50,21,35,Meera-Kumari
5,Ram,Kumar,42.0,BANGALURU,NaN,24-03-2019,22:20,01:10:00,22,20,1,10,Ram-Kumar
6,Mohan,Sharma,52.0,CHENNAI,NaN,01-05-2019,05:50,13:15,5,50,13,15,Mohan-Sharma
7,Rajesh,Pawar,39.0,NaN,Jet Airways,01-03-2019,05:05,08:00,5,5,8,0,Rajesh-Pawar
8,Sanjay,Patil,43.0,NaN,Jet Airways,12-03-2019,08:55,10:25,8,55,10,25,Sanjay-Patil
9,Trishul,Shinde,45.0,Pune,Multiple carriers,27-05-2019,11:25,19:15,11,25,19,15,Trishul-Shinde
10,Sameer,Patil,39.0,Delhi,Jet Airways,12-03-2019,10:25,18:55,10,25,18,55,Sameer-Patil
11,Amol,Mahul,40.0,LUCKNOW,Jet Airways,01-03-2019,05:05,08:00,5,5,8,0,Amol-Mahul
12,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,12-03-2019,08:55,10:25,8,55,10,25,Praveen-Gurjar
13,Sunita,Patil,40.0,CHENNAI,Multiple carriers,27-05-2019,11:25,19:15,11,25,19,15,Sunita-Patil
14,Amol,Mahul,40.0,LUCKNOW,Jet Airways,01-03-2019,05:05,08:00,5,5,8,0,Amol-Mahul
15,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,12-03-2019,08:55,10:25,8,55,10,25,Praveen-Gurjar
16,Sunita,Patil,40.0,CHENNAI,Multiple carriers,27-05-2019,11:25,19:15,11,25,19,15,Sunita-Patil

In [17]:
df.nunique()

calories    3
duration    3
dtype: int64

In [27]:
df['Airline'].unique()

<StringArray>
['IndiGo', 'Air India', 'Jet Airways', nan, 'Multiple carriers']
Length: 5, dtype: str

In [30]:
df['Airline']

0                IndiGo
1             Air India
2           Jet Airways
3                IndiGo
4                IndiGo
5                   NaN
6                   NaN
7           Jet Airways
8           Jet Airways
9     Multiple carriers
10          Jet Airways
11          Jet Airways
12          Jet Airways
13    Multiple carriers
14          Jet Airways
15          Jet Airways
16    Multiple carriers
Name: Airline, dtype: str

In [28]:
df[12:14]

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
12,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,12-03-2019,08:55,10:25,8,55,10,25,Praveen-Gurjar
13,Sunita,Patil,40.0,CHENNAI,Multiple carriers,27-05-2019,11:25,19:15,11,25,19,15,Sunita-Patil

# Loc

In [33]:
df.loc[4:6,['City','Airline']]
df.loc[4:8,['City','Airline']]

        City      Airline
4    LUCKNOW       IndiGo
5  BANGALURU          NaN
6    CHENNAI          NaN
7        NaN  Jet Airways
8        NaN  Jet Airways

# Iloc

In [ ]:
df.iloc[4:6,[3,4]]
df.iloc[4:6,[]]

        City Airline
4    LUCKNOW  IndiGo
5  BANGALURU     NaN

In [2]:
! pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\Niket\AppData\Roaming\Python\Python314\site-packages (3.1.0)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Niket\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.9.0 in C:\Users\Niket\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Niket\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.6)
Requirement already satisfied: six>=1.5 in C:\Users\Niket\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)

In [3]:
import pandas as pd

In [4]:
pd.__version__

'3.1.0'